apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-backend
  namespace: shopmicro
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - shopmicro
    labelSelectors:
      app: backend
